### ISSUE TITLE
您好，请问数据集是没有给全吗？

### ISSUE THREAD

**Issue by printf123** [HKUDS/HGCL#1]
运行的时候发现数据集的文件好像不全

**Comment by cmr123456** [comment]
直接运行的数据文件，可以用数据集目录下的对应的数据处理函数运行一下生成

**Comment by cmr123456** [comment]
如果还有问题，乐意继续解答

**Comment by cmr123456** [comment]
您好 已经将可以直接运行的数据文件的百度网盘链接 放在dataset目录下的readme文件里，如果需要可以下载

**Comment by printf123** [comment]
> 

非常感谢
