### ISSUE TITLE
Yelp数据集

### ISSUE THREAD

**Issue by renameart** [HKUDS/HGCL#11]
你好，认真地读了你的论文，但是对于数据集有些疑问，下载了数据集发现和官方提供地Yelp数据集不太一样。所以能够对Yelp数据集地数据做一些说明吗？
![image](https://github.com/HKUDS/HGCL/assets/61444248/abb195a4-eaf4-467b-bb5d-4b8bd5a6cfac)
比如，在这张截图中，五个矩阵在论文中分别起什么作用？矩阵中地数据分别代表什么意思？期待您的回复，感谢。

**Comment by cmr123456** [comment]
感谢你的提问！！首先，data.pkl是在../dataset/loadMat.py函数产生的，里面会有详细的每个矩阵的生成过程和具体意思。
其次下载的数据集是经过预处理得到模型直接运行的数据，也是通过../dataset/GenerateDistanceMat.py 和 ../dataset/Generate_ICI.py生成的。
希望能帮到你，如果还有问题可以进一步探讨。

**Comment by renameart** [comment]
感谢回复！能否提供一下../dataset/loadMat.py用到的csv文件，可发送到邮箱1713875760@qq.com,不胜感激！

**Comment by Negus25** [comment]
Can you please share the CSV files. 
Thank you!  
nigusdawit16@gmail.com

**Comment by xinyiZN** [comment]
Can you please share the CSV files.
Thank you!
xinyizhou2000s@gmail.com

**Comment by renameart** [comment]
The author don't give me the dataset



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月6日(周五) 晚上6:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [HKUDS/HGCL] Yelp数据集 (Issue #11)




 
Can you please share the CSV files.
 Thank you!
 ***@***.***

**Comment by iexermr** [comment]
> 感谢回复！能否提供一下../dataset/loadMat.py用到的csv文件，可发送到邮箱[1713875760@qq.com](mailto:1713875760@qq.com),不胜感激！

您好，你需要的../dataset/loadMat.py用到的csv文件在dataset/yelp/dataraw.zip中，可以下载下下来

**Comment by iexermr** [comment]
> Can you please share the CSV files. Thank you! [nigusdawit16@gmail.com](mailto:nigusdawit16@gmail.com)
Hello, the CSV file required for "../dataset/loadMat.py" is available in the "dataset/yelp/dataraw.zip" file. You can download it from there.

**Comment by iexermr** [comment]
> Can you please share the CSV files. Thank you! [xinyizhou2000s@gmail.com](mailto:xinyizhou2000s@gmail.com)

Hello, the CSV file required for "../dataset/loadMat.py" is available in the "dataset/yelp/dataraw.zip" file. You can download it from there.

**Comment by Negus25** [comment]
when i load the CSV file the dimension of ratingMat and trustMat is not matched. I mean the number of users must be the same. can you provide the correct file? or the seed you used during the preprocess.

**Comment by FZYTina** [comment]
Can you please share the raw datas of Yelp. I cannot download it in the link of ../dataset/readme. It needs access. Thank you.
