### ISSUE TITLE
Hyperparameter setting

### ISSUE THREAD

**Issue by lrx7156** [HKUDS/HGCL#12]
Why is my result not as good as what was written in the paper? Is it a parameter setting issue

**Comment by iexermr** [comment]
Yes, the parameter settings related to contrastive learning in the code are quite sensitive.

**Comment by imengru** [comment]
> Why is my result not as good as what was written in the paper? Is it a parameter setting issu
Are the dataset and source code you are using the same as mine？ the parameter settings related to contrastive learning in the code are quite sensitive.
