### ISSUE TITLE
main.py: error: argument --ssl_beta: invalid int value: '0.45'

### ISSUE THREAD

**Issue by Jeriousman** [HKUDS/HGCL#4]
I commanded the example code `python main.py --dataset Yelp --ssl_temp 0.5 --ssl_ureg 0.06 --ssl_ireg 0.07 --lr 0.058 --reg 0.05 --ssl_beta 0.45 --rank 3` at directory of HGCL where main.py resides.

But I get this error above. Something must be off?

**Comment by cmr123456** [comment]
Thanks for pointing out our mistake. We have updated our code and it should work now.
