### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by renameart** [HKUDS/HGCL#7]
![image](https://user-images.githubusercontent.com/61444248/232190525-b21688f7-aa21-45b2-b22d-0cba5128debb.png)
Hello, I want to know where is the dataset/Epinions/data.pkl, and  dataset/CiaoDVD/data.pkl is same with other dataset.

**Comment by cmr123456** [comment]
You can download all three datasets from&nbsp;Google Drive.&nbsp;&nbsp;


陈梦如
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月15日(星期六) 下午2:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [HKUDS/HGCL] bug (Issue #7)





 

 Hello, I want to know where is the dataset/Epinions/data.pkl, and  dataset/CiaoDVD/data.pkl is same with other dataset.
