### ISSUE TITLE
new bug 

### ISSUE THREAD

**Issue by renameart** [HKUDS/HGCL#8]
![image](https://github.com/HKUDS/HGCL/assets/61444248/efd20777-db7e-47b7-b8d1-8d7b0033f6ef)
I have make the directory HGCL/History and other directory HGCL/Models

**Comment by cmr123456** [comment]
Thanks for your issue. About it , you may make&nbsp; the directory HGCL/Yelp/History and other directory HGCL/Yelp/Models. I hope it can help you.




陈梦如
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HKUDS/HGCL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月9日(星期二) 晚上9:41
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[HKUDS/HGCL] new bug  (Issue #8)





 

 I have make the directory HGCL/History and other directory HGCL/Models

**Comment by cmr123456** [comment]
Thanks for your issue. About it , you may make&nbsp; the directory HGCL/History/Yelp&nbsp;and other directory HGCL/Models/Yelp. I hope it can help you.




陈梦如
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "HKUDS/HGCL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月9日(星期二) 晚上9:41
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[HKUDS/HGCL] new bug  (Issue #8)





 

 I have make the directory HGCL/History and other directory HGCL/Models

**Comment by renameart** [comment]
Thanks for your reply, I hava debugged it by myself.

**Comment by cmr123456** [comment]
No thanks.




别来无恙
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HKUDS/HGCL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月9日(星期二) 晚上10:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HKUDS/HGCL] new bug  (Issue #8)





 
Thanks for your reply, I hava debugged it by myself.
