### ISSUE TITLE
Missing files in the raw dataset

### ISSUE THREAD

**Issue by CodeStar-Pq** [HKUDS/HGCL#9]
There are only two datasets(ratings.csv and trust.csv) in the raw dataset and there are no category.csv.Can you provide it or tell us about its basic structure.Thanks!

**Comment by cmr123456** [comment]
Thanks for your issue. First, about Epinions and CiaoDVD datasets，you can checks dataset/Epinions/LoadMat.py and will find that 
how to generate categoryMat  and  categoryDict. For Yelp dataset , we already have upload the category.csv to the ../Yelp /raw dataset. If you have questions, we will be happy to communicate further.

**Comment by CodeStar-Pq** [comment]
> Thanks for your issue. First, about Epinions and CiaoDVD datasets，you can checks dataset/Epinions/LoadMat.py and will find that how to generate categoryMat and categoryDict. For Yelp dataset , we already have upload the category.csv to the ../Yelp /raw dataset. If you have questions, we will be happy to communicate further.

Thanks!
